### ISSUE TITLE
Hardcoded wp-content URLs in JS files break plugin in non standard WP installation structures

### ISSUE THREAD

**Issue by richaber** [TheWebShop/bootstrap-shortcodes#19]
Hardcoded wp-content URLS present in grid.js, icons.js, and tabs.js causes some of the TinyMCE shortcode buttons of the plugin to break in certain "non standard" (i.e. version control friendly) installation structures.

Lines in question are:
grid.js line 36: tb_show('Custom Grid', '../wp-content/plugins/bootstrap-shortcodes
icons.js line 11: tb_show('Select icons', '../wp-content/plugins/bootstrap-shortcodes
tabs.js line 10: tb_show('Tab builder', '../wp-content/plugins/bootstrap-shortcodes

Localizing the above scripts to use a variable that references the plugin's actual installation directory would be one potential solution.

**Comment by Sinetheta** [comment]
Wow, did you fix this @No3x back with https://github.com/TheWebShop/bootstrap-shortcodes/issues/25 ?

**Comment by No3x** [comment]
Confirmed as fixed since #25 or WordPress Plugin Repository version 3.0.0. Previous argumentation was right: [TinyMCE's provided](https://github.com/TheWebShop/bootstrap-shortcodes/commit/3380dd46bcf777615412912dca01d16996cbc23b#diff-a8e6f453c0322010085e71c108998a8eR3) `url` is `WP_CONTENT_URL`.
Moving the wp-content directory is fine and supported.
