### ISSUE TITLE
Issue with any shortcode with lightbox (tabs, custom grid, etc.)

### ISSUE THREAD

**Issue by justiny** [TheWebShop/bootstrap-shortcodes#22]
The lightbox appears, but it goes to a 404 page within the site.

Is this a known issue?

Thanks!
Justin

**Comment by Sinetheta** [comment]
Wow, did you fix this @No3x back with https://github.com/TheWebShop/bootstrap-shortcodes/issues/25 ?

**Comment by No3x** [comment]
I'm not sure if this is fixed. I don't remember all changes in #25 well enough.
But let's have a look at grid.js: https://github.com/TheWebShop/bootstrap-shortcodes/commit/3380dd46bcf777615412912dca01d16996cbc23b#diff-a8e6f453c0322010085e71c108998a8e
Instead of calling ```tb_show``` with ```'../wp-content/plugins/bootstrap-shortcodes/js/plugins/grid.html?TB_iframe=1')``` we use the https://github.com/TheWebShop/bootstrap-shortcodes/commit/3380dd46bcf777615412912dca01d16996cbc23b#diff-a8e6f453c0322010085e71c108998a8eR18 instead with a url string provided by tinymce. (So I might have thought: Oh well, rely on this url by the framework - so the other case might be also fixed).
I was never able to reproduce this because I don't have a custom installation with.. (well, just see https://github.com/TheWebShop/bootstrap-shortcodes/issues/22#issuecomment-36363600)

**Comment by No3x** [comment]
Confirmed as fixed since #25 or WordPress Plugin Repository version 3.0.0. Previous argumentation was right: [TinyMCE's provided](https://github.com/TheWebShop/bootstrap-shortcodes/commit/3380dd46bcf777615412912dca01d16996cbc23b#diff-a8e6f453c0322010085e71c108998a8eR3) `url` is `WP_CONTENT_URL`.
Moving the wp-content directory is fine and supported.
