### ISSUE TITLE
Causes Ninja Forms not to load.

### ISSUE THREAD

**Issue by michaelandrewdesign** [TheWebShop/bootstrap-shortcodes#42]
When bootstrap-shortcodes is loaded, http://ninjaforms.com/ Ninja forms modal popup won't sucessfully run. 

-Michael-

**Comment by Mario-M** [comment]
so disabling bootstrap.js under settings will allow bootstrap modals to work again (as long as you are loading bootstrap.js through your theme) however it now breaks tooltips when you disable bootstrap.js.

very frustrating.

**Comment by Sinetheta** [comment]
Ya, I'm not really sure what to say here. We offer the choice to either include Bootstrap or not include Bootstrap.

I don't even see Bootstrap being loaded by Ninja Forms, so I'm guessing that the conflict with their modal was just an unfortunate collision?

I would recommend anyone experiencing similar problems create a custom Bootstrap build for themselves which includes only those components you are interested in.

http://getbootstrap.com/customize/

**Comment by Mario-M** [comment]
From my experience, the modal breaking doesn't have anything to do with Ninja Forms, it has to do with bootstrap.js being loaded twice. When this happens, the modal opens and immediately closes on it's own.

In my theme, I load up bootstrap.min.js through the wp_enqueue_script function, so when Bootstrap Shortcuts load's bootstrap.js, this causes a double load which breaks the modals. 

Going into the Bootstrap Shortcodes settings, disabling bootstrap.js fixes any modal problems and everything else seems to work fine, but for some reason it breaks the tooltips shortcodes. Even though bootstrap.min.js is successfully being loaded by the theme instead of the plugin.

The only difference is that I am loading bootstrap.min.js and you are loading bootstrap.js but I can't think of a reason as to why this would make a difference in the function of the tooltips.

If you need any more info just let me know.

**Comment by Mario-M** [comment]
Okay scratch all that. I guess the issue was when you disable bootstrap.js from the plugin, it doesnt run init.js which initiates the tooltips. Manually adding the tooltips initialization fixed the issue.

**Comment by Sinetheta** [comment]
Glad this everything turned out well.
