### ISSUE TITLE
Tabs UI does not work

### ISSUE THREAD

**Issue by infn8** [TheWebShop/bootstrap-shortcodes#46]
The lightbox style UI for making tabs does not seem to work on WP 4.1.  

It pops up but the plus button does not work nor does switching between tabs.  I have made a screencast showing as much here:  <https://www.youtube.com/watch?v=0ryh_tyCg2I>

Video made in FF latest on mac but chrome mac also does not work.
install of WP is mostly out of the box but the admin pages in particular have NO modifications other than this plugin.

**Comment by Sinetheta** [comment]
Thanks for the detailed report with video @infn8 those lightboxes were some inherited jQuery spaghetti, so if this issue is still around tonight I'll be happy to take a look.

**Comment by No3x** [comment]
Hi @infn8,

you have to scroll down for the green Button 'Create new tab'.

**Comment by infn8** [comment]
I had another look @No3x.  I see no such button.

**Comment by infn8** [comment]
@Sinetheta thanks.  Let me know if you want a hand and I'll take a crack at it in a virgin install.

**Comment by No3x** [comment]
Sorry for assuming this, but I was not able to reproduce this on 4.1 and saw the scroll bar in your video. So it must be a bug.

**Comment by Sinetheta** [comment]
Please do @infn8 I don't use the plugin myself, I mostly just push @No3x's fixes to svn these days ;)

**Comment by No3x** [comment]
That's not true :p ( There is an open pull request (https://github.com/TheWebShop/bootstrap-shortcodes/pull/41) by the way since a while. It's just an approach and I'm not sure if it was theme-related )

**Comment by Sinetheta** [comment]
This was a definite problem. The jQuery include in those admin popups was exploding, which in turn took down Bootstrap and disabled those buttons. I took the opportunity to bump the version and remove the long deprecated `.live` bindings.

That admin interface could probably use an overhaul in the future though. It might be a fun project to make a simple single page app, instead of a bunch of jQuery spaghetti.
